name: Build Obsidian Plugin

on:
  push:
    tags:
      - "v*"
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Compile TypeScript
        run: npm run build

      - name: Check Directory
        run: dir

      - name: Redetect Files
        run: tsc --noEmit

      - name: Pack necessary plugin files
        run: |
          mkdir release
          cp manifest.json release/
          cp styles.css release/ || true
          cp main.js release/

      - name: Export Artifact
        uses: actions/upload-artifact@v4
        with:
          name: performium
          path: release
