name: Daily Build
run-name: Performium Daily Build (#${{ github.run_number }} - v${{ github.run_attempt && github.repository && 'auto' || 'manual' }})

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['latest']
    steps:
      - name: Get current date
        id: date
        run: echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT && echo $DATE
        
      - uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Display Node.js version
        run: node --version

      - name: Install dependencies
        run: npm install

      - name: Fix npm audit issues
        run: npm audit fix --force

      - name: Run build script
        run: bash bashQuickBuild.sh

      - name: Export artifacts
        uses: actions/upload-artifact@v4
        with: 
          name: performium-node-${{ matrix.node-version }}
          path: performium